In [68]:
import numpy as np
import pandas as pd
students = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],

    "Name": [
        "Aarav Sharma", "Priya Verma", "Rahul Mehta", "Sneha Patel",
        "Vikram Singh", "Ananya Gupta", "Rohan Das", "Kavya Nair",
        "Arjun Rao", "Neha Joshi", "Ishaan Kapoor", "Pooja Yadav",
        "Kunal Mishra", "Meera Iyer", "Aditya Jain", "Simran Kaur",
        "Harsh Vyas", "Nidhi Saxena", "Yash Malhotra", "Tanvi Desai"
    ],

    "Age": [18, 19, 20, 18, 21, 19, 20, 18, 22, 19,
            20, 21, 18, 19, 22, 20, 21, 18, 19, 20],

    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "Course": [
        "BCA", "B.Tech", "BSc", "BCom", "BCA",
        "BBA", "BSc", "B.Tech", "BCA", "BCom",
        "BBA", "BSc", "B.Tech", "BCA", "BCom",
        "BBA", "BSc", "B.Tech", "BCA", "BCom"
    ],

    "Marks": [85, 92, 78, 88, 81, 95, 73, 89, 90, 76,
              84, 91, 79, 87, 82, 93, 75, 86, 88, 80],

    "City": [
        "Delhi", "Mumbai", "Pune", "Indore", "Jaipur",
        "Bhopal", "Surat", "Chennai", "Hyderabad", "Lucknow",
        "Nagpur", "Patna", "Kolkata", "Ahmedabad", "Kanpur",
        "Ranchi", "Noida", "Nashik", "Vadodara", "Udaipur"
    ]
}
df = pd.DataFrame(students)

In [69]:
df.head()

   Student_ID          Name  Age  Gender  Course  Marks    City
0         101  Aarav Sharma   18    Male     BCA     85   Delhi
1         102   Priya Verma   19  Female  B.Tech     92  Mumbai
2         103   Rahul Mehta   20    Male     BSc     78    Pune
3         104   Sneha Patel   18  Female    BCom     88  Indore
4         105  Vikram Singh   21    Male     BCA     81  Jaipur

In [70]:
df.tail()

    Student_ID           Name  Age  Gender  Course  Marks      City
15         116    Simran Kaur   20  Female     BBA     93    Ranchi
16         117     Harsh Vyas   21    Male     BSc     75     Noida
17         118   Nidhi Saxena   18  Female  B.Tech     86    Nashik
18         119  Yash Malhotra   19    Male     BCA     88  Vadodara
19         120    Tanvi Desai   20  Female    BCom     80   Udaipur

In [71]:
df.tail(3)

    Student_ID           Name  Age  Gender  Course  Marks      City
17         118   Nidhi Saxena   18  Female  B.Tech     86    Nashik
18         119  Yash Malhotra   19    Male     BCA     88  Vadodara
19         120    Tanvi Desai   20  Female    BCom     80   Udaipur

In [72]:
df.query("Gender == 'Male' ")

    Student_ID           Name  Age Gender  Course  Marks       City
0          101   Aarav Sharma   18   Male     BCA     85      Delhi
2          103    Rahul Mehta   20   Male     BSc     78       Pune
4          105   Vikram Singh   21   Male     BCA     81     Jaipur
6          107      Rohan Das   20   Male     BSc     73      Surat
8          109      Arjun Rao   22   Male     BCA     90  Hyderabad
10         111  Ishaan Kapoor   20   Male     BBA     84     Nagpur
12         113   Kunal Mishra   18   Male  B.Tech     79    Kolkata
14         115    Aditya Jain   22   Male    BCom     82     Kanpur
16         117     Harsh Vyas   21   Male     BSc     75      Noida
18         119  Yash Malhotra   19   Male     BCA     88   Vadodara

In [73]:
df.query(" Age > 18  | Gender == 'Male' ")

    Student_ID           Name  Age  Gender  Course  Marks       City
0          101   Aarav Sharma   18    Male     BCA     85      Delhi
1          102    Priya Verma   19  Female  B.Tech     92     Mumbai
2          103    Rahul Mehta   20    Male     BSc     78       Pune
4          105   Vikram Singh   21    Male     BCA     81     Jaipur
5          106   Ananya Gupta   19  Female     BBA     95     Bhopal
6          107      Rohan Das   20    Male     BSc     73      Surat
8          109      Arjun Rao   22    Male     BCA     90  Hyderabad
9          110     Neha Joshi   19  Female    BCom     76    Lucknow
10         111  Ishaan Kapoor   20    Male     BBA     84     Nagpur
11         112    Pooja Yadav   21  Female     BSc     91      Patna
12         113   Kunal Mishra   18    Male  B.Tech     79    Kolkata
13         114     Meera Iyer   19  Female     BCA     87  Ahmedabad
14         115    Aditya Jain   22    Male    BCom     82     Kanpur
15         116    Simran Kaur   20  Female     BBA     93     Ranchi
16         117     Harsh Vyas   21    Male     BSc     75      Noida
18         119  Yash Malhotra   19    Male     BCA     88   Vadodara
19         120    Tanvi Desai   20  Female    BCom     80    Udaipur

In [74]:
df.query(" Age >= 18  & Gender == 'Male' ")

    Student_ID           Name  Age Gender  Course  Marks       City
0          101   Aarav Sharma   18   Male     BCA     85      Delhi
2          103    Rahul Mehta   20   Male     BSc     78       Pune
4          105   Vikram Singh   21   Male     BCA     81     Jaipur
6          107      Rohan Das   20   Male     BSc     73      Surat
8          109      Arjun Rao   22   Male     BCA     90  Hyderabad
10         111  Ishaan Kapoor   20   Male     BBA     84     Nagpur
12         113   Kunal Mishra   18   Male  B.Tech     79    Kolkata
14         115    Aditya Jain   22   Male    BCom     82     Kanpur
16         117     Harsh Vyas   21   Male     BSc     75      Noida
18         119  Yash Malhotra   19   Male     BCA     88   Vadodara

In [75]:
#df.query(" Age > 18  | ~Gender == 'Male' ") # mistake

In [76]:
df.query(" Age > 18  & ~ (Gender == 'Male' ) ")

    Student_ID          Name  Age  Gender  Course  Marks       City
1          102   Priya Verma   19  Female  B.Tech     92     Mumbai
5          106  Ananya Gupta   19  Female     BBA     95     Bhopal
9          110    Neha Joshi   19  Female    BCom     76    Lucknow
11         112   Pooja Yadav   21  Female     BSc     91      Patna
13         114    Meera Iyer   19  Female     BCA     87  Ahmedabad
15         116   Simran Kaur   20  Female     BBA     93     Ranchi
19         120   Tanvi Desai   20  Female    BCom     80    Udaipur

In [77]:
df.query(" Age < 18")

Empty DataFrame
Columns: [Student_ID, Name, Age, Gender, Course, Marks, City]
Index: []

In [78]:
df.loc[df["Name"] == 'Tanvi Desai', :]

    Student_ID         Name  Age  Gender Course  Marks     City
19         120  Tanvi Desai   20  Female   BCom     80  Udaipur

In [79]:
df.loc[df["Name"] == 'Tanvi Desai']

    Student_ID         Name  Age  Gender Course  Marks     City
19         120  Tanvi Desai   20  Female   BCom     80  Udaipur

In [80]:
df.loc[df["Name"] == 'Tanvi Desai', ['Name','Gender','Course']]

           Name  Gender Course
19  Tanvi Desai  Female   BCom

In [81]:
df.head()

   Student_ID          Name  Age  Gender  Course  Marks    City
0         101  Aarav Sharma   18    Male     BCA     85   Delhi
1         102   Priya Verma   19  Female  B.Tech     92  Mumbai
2         103   Rahul Mehta   20    Male     BSc     78    Pune
3         104   Sneha Patel   18  Female    BCom     88  Indore
4         105  Vikram Singh   21    Male     BCA     81  Jaipur

In [82]:
df.loc[df['Course'] == 'BCA']

    Student_ID           Name  Age  Gender Course  Marks       City
0          101   Aarav Sharma   18    Male    BCA     85      Delhi
4          105   Vikram Singh   21    Male    BCA     81     Jaipur
8          109      Arjun Rao   22    Male    BCA     90  Hyderabad
13         114     Meera Iyer   19  Female    BCA     87  Ahmedabad
18         119  Yash Malhotra   19    Male    BCA     88   Vadodara

In [83]:
#df.loc[df['Course'] == 'BCA', df['Course']] # Error

In [84]:
df.loc[df['Course'] == 'BCA','Course']

0     BCA
4     BCA
8     BCA
13    BCA
18    BCA
Name: Course, dtype: str

In [85]:
df.shape

(20, 7)

In [86]:
df.min()

Student_ID             101
Name          Aarav Sharma
Age                     18
Gender              Female
Course              B.Tech
Marks                   73
City             Ahmedabad
dtype: object

In [87]:
df.max()

Student_ID              120
Name          Yash Malhotra
Age                      22
Gender                 Male
Course                  BSc
Marks                    95
City               Vadodara
dtype: object

In [91]:
# give data me whose std_id is 102 and print only their name
df.loc[df['Student_ID'] == 102 , ['Name']]

          Name
1  Priya Verma

In [90]:
df.head()

   Student_ID          Name  Age  Gender  Course  Marks    City
0         101  Aarav Sharma   18    Male     BCA     85   Delhi
1         102   Priya Verma   19  Female  B.Tech     92  Mumbai
2         103   Rahul Mehta   20    Male     BSc     78    Pune
3         104   Sneha Patel   18  Female    BCom     88  Indore
4         105  Vikram Singh   21    Male     BCA     81  Jaipur

In [92]:
df.max()

Student_ID              120
Name          Yash Malhotra
Age                      22
Gender                 Male
Course                  BSc
Marks                    95
City               Vadodara
dtype: object

In [95]:
#df.std("Stduent_ID") # Error

In [96]:
# find standard deviation of "Student column "
df.Student_ID.std()

np.float64(5.916079783099616)

In [98]:
# find standard deviation of "Student column "
df['Student_ID'].std()

np.float64(5.916079783099616)

In [99]:
# print data whose/where age is greater than 21
df[df['Age'] > 21 ]

    Student_ID         Name  Age Gender Course  Marks       City
8          109    Arjun Rao   22   Male    BCA     90  Hyderabad
14         115  Aditya Jain   22   Male   BCom     82     Kanpur

In [100]:
# print data whose/where age is greater than 21
df.loc[df['Age'] > 21 ]

    Student_ID         Name  Age Gender Course  Marks       City
8          109    Arjun Rao   22   Male    BCA     90  Hyderabad
14         115  Aditya Jain   22   Male   BCom     82     Kanpur

In [101]:
# print data whose/where age is greater than 21
df.query(" Age > 21")

    Student_ID         Name  Age Gender Course  Marks       City
8          109    Arjun Rao   22   Male    BCA     90  Hyderabad
14         115  Aditya Jain   22   Male   BCom     82     Kanpur

In [102]:
# print data whose/where age is greater than 21 , whole data boolean
df['Age'] > 21

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
Name: Age, dtype: bool

In [103]:
df.iloc[:]

    Student_ID           Name  Age  Gender  Course  Marks       City
0          101   Aarav Sharma   18    Male     BCA     85      Delhi
1          102    Priya Verma   19  Female  B.Tech     92     Mumbai
2          103    Rahul Mehta   20    Male     BSc     78       Pune
3          104    Sneha Patel   18  Female    BCom     88     Indore
4          105   Vikram Singh   21    Male     BCA     81     Jaipur
5          106   Ananya Gupta   19  Female     BBA     95     Bhopal
6          107      Rohan Das   20    Male     BSc     73      Surat
7          108     Kavya Nair   18  Female  B.Tech     89    Chennai
8          109      Arjun Rao   22    Male     BCA     90  Hyderabad
9          110     Neha Joshi   19  Female    BCom     76    Lucknow
10         111  Ishaan Kapoor   20    Male     BBA     84     Nagpur
11         112    Pooja Yadav   21  Female     BSc     91      Patna
12         113   Kunal Mishra   18    Male  B.Tech     79    Kolkata
13         114     Meera Iyer   19  Female     BCA     87  Ahmedabad
14         115    Aditya Jain   22    Male    BCom     82     Kanpur
15         116    Simran Kaur   20  Female     BBA     93     Ranchi
16         117     Harsh Vyas   21    Male     BSc     75      Noida
17         118   Nidhi Saxena   18  Female  B.Tech     86     Nashik
18         119  Yash Malhotra   19    Male     BCA     88   Vadodara
19         120    Tanvi Desai   20  Female    BCom     80    Udaipur

In [104]:
# print data whose/where age is greater than 21 , whole data boolean
[df['Age'] > 21]  # index Added

[0     False
 1     False
 2     False
 3     False
 4     False
 5     False
 6     False
 7     False
 8      True
 9     False
 10    False
 11    False
 12    False
 13    False
 14     True
 15    False
 16    False
 17    False
 18    False
 19    False
 Name: Age, dtype: bool]

In [105]:
df.iloc[0:9] # print data when index starts with 0 to 9

   Student_ID          Name  Age  Gender  Course  Marks       City
0         101  Aarav Sharma   18    Male     BCA     85      Delhi
1         102   Priya Verma   19  Female  B.Tech     92     Mumbai
2         103   Rahul Mehta   20    Male     BSc     78       Pune
3         104   Sneha Patel   18  Female    BCom     88     Indore
4         105  Vikram Singh   21    Male     BCA     81     Jaipur
5         106  Ananya Gupta   19  Female     BBA     95     Bhopal
6         107     Rohan Das   20    Male     BSc     73      Surat
7         108    Kavya Nair   18  Female  B.Tech     89    Chennai
8         109     Arjun Rao   22    Male     BCA     90  Hyderabad

In [107]:
# print data where
df.iloc[1:18:2]

    Student_ID          Name  Age  Gender  Course  Marks       City
1          102   Priya Verma   19  Female  B.Tech     92     Mumbai
3          104   Sneha Patel   18  Female    BCom     88     Indore
5          106  Ananya Gupta   19  Female     BBA     95     Bhopal
7          108    Kavya Nair   18  Female  B.Tech     89    Chennai
9          110    Neha Joshi   19  Female    BCom     76    Lucknow
11         112   Pooja Yadav   21  Female     BSc     91      Patna
13         114    Meera Iyer   19  Female     BCA     87  Ahmedabad
15         116   Simran Kaur   20  Female     BBA     93     Ranchi
17         118  Nidhi Saxena   18  Female  B.Tech     86     Nashik

In [ ]:
# data cleaning and preprocessing
# handling missing data