In [ ]:
import numpy as np
import pandas as pd
students = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],

    "Name": [
        "Aarav Sharma", "Priya Verma", "Rahul Mehta", "Sneha Patel",
        "Vikram Singh", "Ananya Gupta", "Rohan Das", "Kavya Nair",
        "Arjun Rao", "Neha Joshi", "Ishaan Kapoor", "Pooja Yadav",
        "Kunal Mishra", "Meera Iyer", "Aditya Jain", "Simran Kaur",
        "Harsh Vyas", "Nidhi Saxena", "Yash Malhotra", "Tanvi Desai"
    ],

    "Age": [18, 19, 20, 18, 21, 19, 20, 18, 22, 19,
            20, 21, 18, 19, 22, 20, 21, 18, 19, 20],

    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "Course": [
        "BCA", "B.Tech", "BSc", "BCom", "BCA",
        "BBA", "BSc", "B.Tech", "BCA", "BCom",
        "BBA", "BSc", "B.Tech", "BCA", "BCom",
        "BBA", "BSc", "B.Tech", "BCA", "BCom"
    ],

    "Marks": [85, 92, 78, 88, 81, 95, 73, 89, 90, 76,
              84, 91, 79, 87, 82, 93, 75, 86, 88, 80],

    "City": [
        "Delhi", "Mumbai", "Pune", "Indore", "Jaipur",
        "Bhopal", "Surat", "Chennai", "Hyderabad", "Lucknow",
        "Nagpur", "Patna", "Kolkata", "Ahmedabad", "Kanpur",
        "Ranchi", "Noida", "Nashik", "Vadodara", "Udaipur"
    ]
}
df = pd.DataFrame(students)

In [ ]:
students = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],

    "Name": [
        "Aarav Sharma", "Priya Verma", "Rahul Mehta", "Sneha Patel",
        "Vikram Singh", "Ananya Gupta", "Rohan Das", "Kavya Nair",
        "Arjun Rao", "Neha Joshi", "Ishaan Kapoor", "Pooja Yadav",
        "Kunal Mishra", "Meera Iyer", "Aditya Jain", "Simran Kaur",
        "Harsh Vyas", "Nidhi Saxena", "Yash Malhotra", "Tanvi Desai"
    ],

    "Age": [18, 19, 20, 18, 21, 19, 20, 18, 22, 19,
            20, 21, 18, 19, 22, 20, 21, 18, 19, 20],

    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "Course": [
        "BCA", "B.Tech", "BSc", "BCom", "BCA",
        "BBA", "BSc", "B.Tech", "BCA", "BCom",
        "BBA", "BSc", "B.Tech", "BCA", "BCom",
        "BBA", "BSc", "B.Tech", "BCA", "BCom"
    ],

    "Marks": [85, 92, 78, 88, 81, 95, 73, 89, 90, 76,
              84, 91, 79, 87, 82, 93, 75, 86, 88, 80],

    "City": [
        "Delhi", "Mumbai", "Pune", "Indore", "Jaipur",
        "Bhopal", "Surat", "Chennai", "Hyderabad", "Lucknow",
        "Nagpur", "Patna", "Kolkata", "Ahmedabad", "Kanpur",
        "Ranchi", "Noida", "Nashik", "Vadodara", "Udaipur"
    ]
}
df = pd.DataFrame(students)
print(df)

In [ ]:
students = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],

    "Name": [
        "Aarav Sharma", "Priya Verma", "Rahul Mehta", "Sneha Patel",
        "Vikram Singh", "Ananya Gupta", "Rohan Das", "Kavya Nair",
        "Arjun Rao", "Neha Joshi", "Ishaan Kapoor", "Pooja Yadav",
        "Kunal Mishra", "Meera Iyer", "Aditya Jain", "Simran Kaur",
        "Harsh Vyas", "Nidhi Saxena", "Yash Malhotra", "Tanvi Desai"
    ],

    "Age": [18, 19, 20, 18, 21, 19, 20, 18, 22, 19,
            20, 21, 18, 19, 22, 20, 21, 18, 19, 20],

    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "Course": [
        "BCA", "B.Tech", "BSc", "BCom", "BCA",
        "BBA", "BSc", "B.Tech", "BCA", "BCom",
        "BBA", "BSc", "B.Tech", "BCA", "BCom",
        "BBA", "BSc", "B.Tech", "BCA", "BCom"
    ],

    "Marks": [85, 92, 78, 88, 81, 95, 73, 89, 90, 76,
              84, 91, 79, 87, 82, 93, 75, 86, 88, 80],

    "City": [
        "Delhi", "Mumbai", "Pune", "Indore", "Jaipur",
        "Bhopal", "Surat", "Chennai", "Hyderabad", "Lucknow",
        "Nagpur", "Patna", "Kolkata", "Ahmedabad", "Kanpur",
        "Ranchi", "Noida", "Nashik", "Vadodara", "Udaipur"
    ]
}
df = pd.DataFrame(students)
print(df.T)

In [ ]:
students = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],

    "Name": [
        "Aarav Sharma", "Priya Verma", "Rahul Mehta", "Sneha Patel",
        "Vikram Singh", "Ananya Gupta", "Rohan Das", "Kavya Nair",
        "Arjun Rao", "Neha Joshi", "Ishaan Kapoor", "Pooja Yadav",
        "Kunal Mishra", "Meera Iyer", "Aditya Jain", "Simran Kaur",
        "Harsh Vyas", "Nidhi Saxena", "Yash Malhotra", "Tanvi Desai"
    ],

    "Age": [18, 19, 20, 18, 21, 19, 20, 18, 22, 19,
            20, 21, 18, 19, 22, 20, 21, 18, 19, 20],

    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "Course": [
        "BCA", "B.Tech", "BSc", "BCom", "BCA",
        "BBA", "BSc", "B.Tech", "BCA", "BCom",
        "BBA", "BSc", "B.Tech", "BCA", "BCom",
        "BBA", "BSc", "B.Tech", "BCA", "BCom"
    ],

    "Marks": [85, 92, 78, 88, 81, 95, 73, 89, 90, 76,
              84, 91, 79, 87, 82, 93, 75, 86, 88, 80],

    "City": [
        "Delhi", "Mumbai", "Pune", "Indore", "Jaipur",
        "Bhopal", "Surat", "Chennai", "Hyderabad", "Lucknow",
        "Nagpur", "Patna", "Kolkata", "Ahmedabad", "Kanpur",
        "Ranchi", "Noida", "Nashik", "Vadodara", "Udaipur"
    ]
}
df = pd.DataFrame(students)
print(df.sort_values(by='Marks',ascending=False))

In [ ]:
print(df)

In [ ]:
print(df)

In [ ]:
print(df['Name'])

print data of the students whose marks are greater than 60

In [ ]:
print(df['Marks'] >= 60)

In [ ]:
df[df["Marks"] >= 60]

In [ ]:
df[(df['Marks'] < 90 ) & (df['Gender'] == 'Male')]

In [ ]:
df[df['Course'] == "BCA"]

In [ ]:
df[['Name','Course']][
    (df['Marks'] < 90) &
    (df['Gender'] == 'Male')
]

In [ ]:
df.loc[
    (df['Marks'] > 80 ) &
    (df['City']=='Delhi'), ['Name','Gender','Course']
]

In [ ]:
df.loc[
    df['Marks'] > 80,
    ['Name', 'Marks']
]

In [ ]:
students_1 = {
    "StdID": [
        1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020,
        1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030,
        1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040,
        1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050,
        1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060,
        1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070,
        1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080,
        1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090,
        1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100
    ],

    "Name": [f"Student_{i}" for i in range(1, 101)],

    "Age": [
        18,19,20,21,22,18,19,20,21,22,
        18,19,20,21,22,18,19,20,21,22,
        18,19,20,21,22,18,19,20,21,22,
        18,19,20,21,22,18,19,20,21,22,
        18,19,20,21,22,18,19,20,21,22,
        18,19,20,21,22,18,19,20,21,22,
        18,19,20,21,22,18,19,20,21,22,
        18,19,20,21,22,18,19,20,21,22,
        18,19,20,21,22,18,19,20,21,22,
        18,19,20,21,22,18,19,20,21,22
    ],

    "Course": [
        "BCA", "BTech", "BSc", "BCom", "BBA"
    ] * 20,

    "Phone_No": [
        9876500001 + i for i in range(100)
    ],

    "Fee": [
        35000, 45000, 30000, 28000, 40000
    ] * 20,

    "City": [
        "Delhi", "Mumbai", "Pune", "Indore", "Jaipur",
        "Bhopal", "Surat", "Chennai", "Hyderabad", "Lucknow"
    ] * 10
}
df_1 = pd.DataFrame(students_1)

In [ ]:
df_1

In [59]:
df_1.loc[
    (df_1['Fee'] > 35000) , ['Age','City', 'StdID']
]

    Age     City  StdID
1    19   Mumbai   1002
4    22   Jaipur   1005
6    19    Surat   1007
9    22  Lucknow   1010
11   19   Mumbai   1012
14   22   Jaipur   1015
16   19    Surat   1017
19   22  Lucknow   1020
21   19   Mumbai   1022
24   22   Jaipur   1025
26   19    Surat   1027
29   22  Lucknow   1030
31   19   Mumbai   1032
34   22   Jaipur   1035
36   19    Surat   1037
39   22  Lucknow   1040
41   19   Mumbai   1042
44   22   Jaipur   1045
46   19    Surat   1047
49   22  Lucknow   1050
51   19   Mumbai   1052
54   22   Jaipur   1055
56   19    Surat   1057
59   22  Lucknow   1060
61   19   Mumbai   1062
64   22   Jaipur   1065
66   19    Surat   1067
69   22  Lucknow   1070
71   19   Mumbai   1072
74   22   Jaipur   1075
76   19    Surat   1077
79   22  Lucknow   1080
81   19   Mumbai   1082
84   22   Jaipur   1085
86   19    Surat   1087
89   22  Lucknow   1090
91   19   Mumbai   1092
94   22   Jaipur   1095
96   19    Surat   1097
99   22  Lucknow   1100

In [61]:
df.head(3)

   Student_ID          Name  Age  Gender  Course  Marks    City
0         101  Aarav Sharma   18    Male     BCA     85   Delhi
1         102   Priya Verma   19  Female  B.Tech     92  Mumbai
2         103   Rahul Mehta   20    Male     BSc     78    Pune

In [66]:
df.drop(columns='Gender',inplace=True)

In [67]:
df

    Student_ID           Name  Age  Course  Marks       City
0          101   Aarav Sharma   18     BCA     85      Delhi
1          102    Priya Verma   19  B.Tech     92     Mumbai
2          103    Rahul Mehta   20     BSc     78       Pune
3          104    Sneha Patel   18    BCom     88     Indore
4          105   Vikram Singh   21     BCA     81     Jaipur
5          106   Ananya Gupta   19     BBA     95     Bhopal
6          107      Rohan Das   20     BSc     73      Surat
7          108     Kavya Nair   18  B.Tech     89    Chennai
8          109      Arjun Rao   22     BCA     90  Hyderabad
9          110     Neha Joshi   19    BCom     76    Lucknow
10         111  Ishaan Kapoor   20     BBA     84     Nagpur
11         112    Pooja Yadav   21     BSc     91      Patna
12         113   Kunal Mishra   18  B.Tech     79    Kolkata
13         114     Meera Iyer   19     BCA     87  Ahmedabad
14         115    Aditya Jain   22    BCom     82     Kanpur
15         116    Simran Kaur   20     BBA     93     Ranchi
16         117     Harsh Vyas   21     BSc     75      Noida
17         118   Nidhi Saxena   18  B.Tech     86     Nashik
18         119  Yash Malhotra   19     BCA     88   Vadodara
19         120    Tanvi Desai   20    BCom     80    Udaipur

In [68]:
df

    Student_ID           Name  Age  Course  Marks       City
0          101   Aarav Sharma   18     BCA     85      Delhi
1          102    Priya Verma   19  B.Tech     92     Mumbai
2          103    Rahul Mehta   20     BSc     78       Pune
3          104    Sneha Patel   18    BCom     88     Indore
4          105   Vikram Singh   21     BCA     81     Jaipur
5          106   Ananya Gupta   19     BBA     95     Bhopal
6          107      Rohan Das   20     BSc     73      Surat
7          108     Kavya Nair   18  B.Tech     89    Chennai
8          109      Arjun Rao   22     BCA     90  Hyderabad
9          110     Neha Joshi   19    BCom     76    Lucknow
10         111  Ishaan Kapoor   20     BBA     84     Nagpur
11         112    Pooja Yadav   21     BSc     91      Patna
12         113   Kunal Mishra   18  B.Tech     79    Kolkata
13         114     Meera Iyer   19     BCA     87  Ahmedabad
14         115    Aditya Jain   22    BCom     82     Kanpur
15         116    Simran Kaur   20     BBA     93     Ranchi
16         117     Harsh Vyas   21     BSc     75      Noida
17         118   Nidhi Saxena   18  B.Tech     86     Nashik
18         119  Yash Malhotra   19     BCA     88   Vadodara
19         120    Tanvi Desai   20    BCom     80    Udaipur